const actionTypes = {
	'APP_INIT': 'APP_INIT',
	'USER_INIT': 'USER_INIT',
	'USER_LOADING': 'USER_LOADING',
	'USER_LOGOUT': 'USER_LOGOUT',
	'USER_DATA': 'USER_DATA',
	'MEET_LOADING': 'MEET_LOADING',
	'MEET_CONNECT': 'MEET_CONNECT',
	'MEET_CLOSE': 'MEET_CLOSE',
	'DOC_LOADING': 'DOC_LOADING',
	'DOC_LIST': 'DOC_LIST',
	'FOLDER_LIST': 'FOLDER_LIST',
	'FOLDER_ADD': 'FOLDER_ADD',
}

export default actionTypes
